version: 2
updates:
    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "weekly"
          day: monday
          time: "12:00"
          timezone: Europe/London
      reviewers:
          - "edhgoose"
      labels:
          - dependencies
      target-branch: "development"
